language: php

php:
  - 5.6.4
  - 7

env:
  global:
    - setup=basic


sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi


script: phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --access-token="9857f9bb4b1c260b94eb773a541d6e42e05db0db45d5a25757590276d5e50445" --format=php-clover coverage.clover
