language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --access-token="ae78dedc6e6afd791bba718b052cdd6f88aba25ab56d81bc65ca75867491b18a" --format=php-clover coverage.clover
